version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./dockerfile
    image: queue
    container_name: queue
    ports:
      - 3000:3000
    networks:
      - queue

networks:
  queue:
    driver: brigde

