global:
   scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
     - targets:
        - 'prom:9090'

  - job_name: aula
    honor_timestamps: true
    scheme: http
    follow_redirects: true

    static_configs:
    - targets: 
      - 'app:3001'

  - job_name: node_exporter
    honor_timestamps: true
    scheme: http
    follow_redirects: true

    static_configs:
    - targets: 
      - 'node_exporter:9100'